// ignore_for_file: non_constant_identifier_names

class ColumnConfig {
  const ColumnConfig();

  final List<Map<String, dynamic>> REFERENCE_COLUMNS_CONFIG = const [
    {
      "name": "id",
      "datatype": "uuid",
      "description": "Unique Id for the column. This is the Primary Key",
      "columnorder": 100,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": true,
      "isdefault": true,
      "formField": {},
    },
    {
      "name": "referenceid",
      "datatype": "int",
      "description": "ReferenceId for the Column",
      "columnorder": 2,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": true,
      "formField": {
        "name": "referenceid",
        "inputtype": "text",
        "hinttext": {'en': 'Human Readable Id for the data'},
        "labels": {'en': 'ReferenceId(RID)'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "ReferenceId is a required field"}
          },
          {
            "validationtype": "regex",
            "validate": "^[0-9]+\$",
            "messages": {"en": "ReferenceId should have numbers only"}
          },
        ],
        "defaultvisibility": true,
        "iseditable": true,
        "maxlines": 1,
      },
    },
    {
      "name": "userroles",
      "datatype": "list<uuid>",
      "description": "List of User Roles, who has access to this data",
      "columnorder": 5,
      "encrypt": false,
      "isnullable": false,
      "isrequired": false,
      "issearchable": true,
      "isunique": false,
      "formField": {
        "name": "userroles",
        "inputtype": "filterchip",
        "hinttext": {'en': 'Select userRoles who can access this data'},
        "labels": {'en': 'User Roles'},
        "validations": [],
        "defaultvisibility": true,
        "iseditable": true,
        "maxitemstoselect": 10,
        "optionsRef": "userrole",
      },
    },
    {
      "name": "name",
      "datatype": "text",
      "description": "Name for the data",
      "columnorder": 1,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": true,
      "formField": {
        "name": "name",
        "inputtype": "text",
        "hinttext": {'en': 'Name for the data'},
        "labels": {'en': 'Name'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "Name is a required field"}
          },
          {
            "validationtype": "regex",
            "validate": "^[0-9a-zA-z]+\$",
            "messages": {"en": "Name should have alphabets and numbers only"}
          },
        ],
        "defaultvisibility": true,
        "iseditable": true,
        "maxlines": 1,
      },
    },
    {
      "name": "labels",
      "datatype": "map<text,text>",
      "description": "Multilingual Labels to use in the UI",
      "columnorder": 3,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": false,
      "isunique": false,
      "formField": {
        "name": "labels",
        "inputtype": "dialog",
        "hinttext": {'en': 'Multilingual Labels to use in the UI'},
        "labels": {'en': 'Labels'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "Labels is a required field"}
          }
        ],
        "defaultvisibility": true,
        "iseditable": true,
      },
    },
    {
      "name": "displayorder",
      "datatype": "int",
      "description": "Display Order for the data in the table",
      "columnorder": 10,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": false,
      "isunique": true,
      "formField": {
        "name": "displayorder",
        "inputtype": "text",
        "hinttext": {'en': 'Enter display order for the data'},
        "labels": {'en': 'Display Order'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "Display Order is a required field"}
          },
          {
            "validationtype": "regex",
            "validate": "^[0-9]+\$",
            "messages": {"en": "Display Order should have Positive numbers only"}
          },
        ],
        "defaultvisibility": true,
        "iseditable": true,
        "maxlines": 1,
      },
    },
    {
      "name": "status",
      "datatype": "text",
      "description": "Status of the data in the table",
      "columnorder": 8,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": false,
      "formField": {
        "name": "status",
        "inputtype": "dropdown",
        "hinttext": {'en': 'Select status for the data'},
        "labels": {'en': 'Status'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "Status is a required field"}
          }
        ],
        "defaultvisibility": true,
        "iseditable": true,
        "maxitemstoselect": 10,
        "optionsRef": "status",
      },
    },
    {
      "name": "created_on",
      "datatype": "timestamp",
      "description": "Data Creation Timestamp",
      "columnorder": 11,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": false,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "created_by",
      "datatype": "uuid",
      "description": "UserId of the data creator",
      "columnorder": 11,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "updated_on",
      "datatype": "timestamp",
      "description": "Data Updation Timestamp",
      "columnorder": 16,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": false,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "updated_by",
      "datatype": "uuid",
      "description": "UserId of the Data Updater",
      "columnorder": 17,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "active",
      "datatype": "boolean",
      "description": "Active status of the column",
      "columnorder": 7,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": true,
      "formField": {
        "name": "active",
        "inputtype": "switch",
        "hinttext": {'en': 'Is the data Active?'},
        "labels": {'en': 'Active'},
        "validations": [],
        "defaultvisibility": true,
        "iseditable": true,
        "defaultvalue": true,
      },
    }
  ];

  final List<Map<String, dynamic>> TRANSACTION_COLUMNS_CONFIG = const [
    {
      "name": "id",
      "datatype": "uuid",
      "description": "Unique Id for the column. This is the Primary Key",
      "columnorder": 100,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": true,
      "isdefault": true,
      "formField": {},
    },
    // {
    //   "name": "referenceid",
    //   "datatype": "int",
    //   "description": "",
    //   "encrypt": false,
    //   "isnullable": false,
    //   "isrequired": true,
    //   "issearchable": true,
    //   "isunique": true,
    //   "formField": {
    //     "name": "referenceid",
    //     "inputtype": "text",
    //     "hinttext": {'en': 'Human Readable Id for the data'},
    //     "labels": {'en': 'ReferenceId(RID)'},
    //     "validations": [
    //       {
    //         "validationtype": "mandatory",
    //         "validate": true,
    //         "messages": {"en": "ReferenceId is a required field"}
    //       },
    //       {
    //         "validationtype": "regex",
    //         "validate": "^[0-9]+\$",
    //         "messages": {"en": "ReferenceId should have numbers only"}
    //       },
    //     ],
    //     "defaultvisibility": true,
    //     "iseditable": true,
    //     "maxlines": 1,
    //   },
    // },
    // {
    //   "name": "userroles",
    //   "datatype": "list",
    //   "description": "List of User Roles, who has access to this data",
    //   "encrypt": false,
    //   "isnullable": false,
    //   "isrequired": false,
    //   "issearchable": true,
    //   "isunique": false,
    //   "formField": {
    //     "name": "userroles",
    //     "inputtype": "filterchip",
    //     "hinttext": {'en': 'Select userRoles who can access this data'},
    //     "labels": {'en': 'User Roles'},
    //     "validations": [],
    //     "defaultvisibility": true,
    //     "iseditable": true,
    //     "maxitemstoselect": 10,
    //     "optionsRef": "userrole",
    //   },
    // },
    {
      "name": "name",
      "datatype": "text",
      "description": "Name for the data",
      "columnorder": 1,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": true,
      "formField": {
        "name": "name",
        "inputtype": "text",
        "hinttext": {'en': 'Name for the data'},
        "labels": {'en': 'Name'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "Name is a required field"}
          },
          {
            "validationtype": "regex",
            "validate": "^[0-9a-zA-z]+\$",
            "messages": {"en": "Name should have alphabets and numbers only"}
          },
        ],
        "defaultvisibility": true,
        "iseditable": true,
        "maxlines": 1,
      },
    },
    // {
    //   "name": "labels",
    //   "datatype": "map<text,text>",
    //   "description": "Multilingual Labels to use in the UI",
    //   "encrypt": false,
    //   "isnullable": false,
    //   "isrequired": true,
    //   "issearchable": false,
    //   "isunique": false,
    //   "formField": {
    //     "name": "labels",
    //     "inputtype": "dialog",
    //     "hinttext": {'en': 'Multilingual Labels to use in the UI'},
    //     "labels": {'en': 'Labels'},
    //     "validations": [
    //       {
    //         "validationtype": "mandatory",
    //         "validate": true,
    //         "messages": {"en": "Labels is a required field"}
    //       }
    //     ],
    //     "defaultvisibility": true,
    //     "iseditable": true,
    //   },
    // },
    {
      "name": "status",
      "datatype": "text",
      "description": "Status of the data in the table",
      "columnorder": 8,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": false,
      "formField": {
        "name": "status",
        "inputtype": "dropdown",
        "hinttext": {'en': 'Select status for the data'},
        "labels": {'en': 'Status'},
        "validations": [
          {
            "validationtype": "mandatory",
            "validate": true,
            "messages": {"en": "Status is a required field"}
          }
        ],
        "defaultvisibility": true,
        "iseditable": true,
        "maxitemstoselect": 10,
        "optionsRef": "status",
      },
    },
    {
      "name": "created_on",
      "datatype": "timestamp",
      "description": "Data Creation Timestamp",
      "columnorder": 11,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": false,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "created_by",
      "datatype": "uuid",
      "description": "UserId of the data creator",
      "columnorder": 12,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "updated_on",
      "datatype": "timestamp",
      "description": "Data Updation Timestamp",
      "columnorder": 16,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": false,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    {
      "name": "updated_by",
      "datatype": "uuid",
      "description": "UserId of the Data Updater",
      "columnorder": 17,
      "encrypt": false,
      "isnullable": false,
      "isrequired": true,
      "issearchable": true,
      "isunique": false,
      "formField": {},
      "isdefault": true,
    },
    // {
    //   "name": "active",
    //   "datatype": "boolean",
    //   "description": "",
    //   "encrypt": false,
    //   "isnullable": false,
    //   "isrequired": true,
    //   "issearchable": true,
    //   "isunique": true,
    //   "formField": {
    //     "name": "active",
    //     "inputtype": "switch",
    //     "hinttext": {'en': 'Is the data Active?'},
    //     "labels": {'en': 'Active'},
    //     "validations": [],
    //     "defaultvisibility": true,
    //     "iseditable": true,
    //     "defaultvalue": true,
    //   },
    // }
  ];
}
